### ISSUE TITLE
Provide a way to get meaningful data from the sensor

### ISSUE THREAD

**Issue by TheButlah** [eldruin/bmi160-rs#2]
the data returned is in `i16` format. Without a way to access the sensor range, I can't convert this to a float.

**Comment by eldruin** [comment]
The sensor range will depend on the parameters that you have set.
You can have a look at the [datasheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmi160-ds000.pdf) to see how to perform a conversion.
I would welcome code that does the scaling in this crate, though.
You can have a look [here](https://github.com/eldruin/lsm303agr-rs/blob/58c8b327dc7d7fceeee7025e63a44e308beb3480/src/types.rs#L79) for an example.

**Comment by TheButlah** [comment]
Once I implement it and test it in my code, I can implement a PR to add functionality for reading FSR

**Comment by thedevleon** [comment]
> Once I implement it and test it in my code, I can implement a PR to add functionality for reading FSR

Any progress on this?

**Comment by thedevleon** [comment]
I guess code from here could be integrated?
https://github.com/SlimeVR/SlimeVR-Rust/blob/main/firmware/src/imu/drivers/bmi160/mod.rs

**Comment by TheButlah** [comment]
Yes feel free to use the code - I haven't been working on this recently but yes it did seem to be working.

**Comment by TheButlah** [comment]
From what I remember, the maintainer didn't want to bump the MSRV and I use plenty of const code in what you linked. So I didn't submit a PR at the time.

**Comment by eldruin** [comment]
As I said, please feel free to add support for that here.
Over in #1 I preferred to remove the `const` qualifier because it was just [one trivial function](https://github.com/eldruin/bmi160-rs/pull/1/files).
Bumping the MSRV is fine.

**Comment by eldruin** [comment]
Fixed in #9 and published in [1.1.0](https://github.com/eldruin/bmi160-rs/releases/tag/v1.1.0).
Thanks everybody!
