### ISSUE TITLE
SPI interface confusion 

### ISSUE THREAD

**Issue by Lance-Kraakman** [eldruin/bmi160-rs#3]
Hi, sorry this is more of a question then an issue. 

I've been trying to get this crate working with through an SPI interface on an esp32 and haven't had much success.

It is my understanding that the read bit should be set when reading a register.

![image](https://user-images.githubusercontent.com/44858574/226318556-db24675a-019a-43b5-a7cb-0e8698aef70a.png)

When I look at interface.rs I see that the read bit is being set when writing to the device instead of when reading.
for example: 

      fn write_register(&mut self, register: u8, data: u8) -> Result<(), Self::Error> {
              self.cs.set_low().map_err(Error::Pin)?;
              let payload: [u8; 2] = [register + 0x80, data];
              let result = self.spi.write(&payload).map_err(Error::Comm);
      
              self.cs.set_high().map_err(Error::Pin)?;
              result
          }

I was wondering if you could guide me on this, or am I just reading the datasheet completely wrong, tia.

**Comment by eldruin** [comment]
Interesting. Thank you for pointing this out.
It certainly seems like I have swapped the read bit logic for SPI.
I have always used it through I2C so I haven't noticed.
Could you open a PR fixing the logic?

**Comment by Lance-Kraakman** [comment]
> Could you open a PR fixing the logic?

Yep, will do 😀
